import { useState, useEffect } from 'react';
import { FiArrowRight, FiCheckCircle } from 'react-icons/fi';
import Header from '../components/Header';
import Footer from '../components/Footer';
import axios from 'axios';

const API_BASE = 'http://localhost:5000/api';

const getDifficultyColor = (difficulty) => {
  switch (difficulty) {
    case 'Easy': case 'Beginner': return 'bg-green-100 text-green-700';
    case 'Medium': case 'Intermediate': return 'bg-yellow-100 text-yellow-700';
    case 'Hard': case 'Advanced': return 'bg-red-100 text-red-700';
    default: return 'bg-gray-100 text-gray-700';
  }
};

const InterviewPrep = () => {
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [activeCategory, setActiveCategory] = useState('All');

  const isAuthenticated = !!localStorage.getItem('token');

  useEffect(() => {
    if (!isAuthenticated) return;
    const fetchQuestions = async () => {
      setLoading(true);
      try {
        const token = localStorage.getItem('token');
        const res = await axios.get(`${API_BASE}/recommendations`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        setQuestions(res.data.interviewQuestions || []);
      } catch (err) {
        console.error('Interview prep fetch error:', err);
        setError('Failed to load interview questions.');
      } finally {
        setLoading(false);
      }
    };
    fetchQuestions();
  }, []);

  const categories = ['All', ...new Set(questions.map((q) => q.category).filter(Boolean))];
  const filtered = activeCategory === 'All' ? questions : questions.filter((q) => q.category === activeCategory);

  const tips = [
    { title: 'Research the Company', description: "Understand the company's mission, values, recent news, and culture before the interview." },
    { title: 'Practice Common Questions', description: 'Prepare answers for frequently asked questions like "Tell me about yourself" and "Why do you want this job?"' },
    { title: 'Prepare Your Stories', description: 'Have 5-7 compelling stories ready that demonstrate your skills and achievements.' },
    { title: 'Ask Smart Questions', description: 'Prepare thoughtful questions about the role, team, and company to show genuine interest.' },
    { title: 'Mock Interview Practice', description: 'Practice with friends, mentors, or use our mock interview tool to build confidence.' },
    { title: 'Follow Up After', description: 'Send a thank you email within 24 hours reiterating your interest and key points discussed.' },
  ];

  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Header />

      {/* Hero Section */}
      <section className="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <h1 className="text-5xl lg:text-6xl font-bold mb-6">Interview Preparation</h1>
          <p className="text-xl text-gray-300 max-w-2xl">
            Personalized interview questions generated by AI based on your career goals and profile.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <div className="flex-1 py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">

          {/* Interview Questions from DB */}
          <div className="mb-20">
            <h2 className="text-4xl font-bold mb-8 text-slate-900">Your Interview Questions</h2>

            {loading && (
              <div className="flex items-center justify-center py-12">
                <div className="animate-spin rounded-full h-10 w-10 border-4 border-pink-500 border-t-transparent"></div>
                <span className="ml-4 text-gray-600">Loading interview questions...</span>
              </div>
            )}

            {error && (
              <div className="bg-red-50 border border-red-200 text-red-700 px-6 py-4 rounded-lg mb-6">{error}</div>
            )}

            {!isAuthenticated && (
              <div className="bg-blue-50 border border-blue-200 text-blue-700 px-6 py-4 rounded-lg mb-6">
                Please <a href="/login" className="font-semibold underline">sign in</a> to see your personalized interview questions.
              </div>
            )}

            {!loading && isAuthenticated && questions.length === 0 && !error && (
              <div className="text-center py-12 text-gray-500">
                <p>No interview questions found. Complete your profile to get personalized questions.</p>
              </div>
            )}

            {!loading && questions.length > 0 && (
              <>
                {/* Category Filter */}
                <div className="flex flex-wrap gap-2 mb-6">
                  {categories.map((cat) => (
                    <button
                      key={cat}
                      onClick={() => setActiveCategory(cat)}
                      className={`px-4 py-2 rounded-full text-sm font-semibold transition ${
                        activeCategory === cat
                          ? 'bg-gradient-to-r from-pink-500 to-purple-600 text-white'
                          : 'bg-white border border-gray-300 text-gray-700 hover:bg-gray-50'
                      }`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>

                <div className="space-y-4">
                  {filtered.map((q, i) => (
                    <div key={i} className="bg-white border-2 border-gray-200 hover:border-cyan-500 rounded-2xl p-6 shadow-md hover:shadow-lg transition">
                      <div className="flex items-start justify-between mb-3">
                        <h3 className="text-lg font-semibold text-gray-900 flex-1">{q.question}</h3>
                        <span className={`px-3 py-1 rounded-full text-xs font-semibold whitespace-nowrap ml-4 ${getDifficultyColor(q.difficulty)}`}>
                          {q.difficulty}
                        </span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-gray-600 bg-gray-100 px-3 py-1 rounded">
                          {q.category}
                        </span>
                        <button className="text-pink-500 hover:text-pink-600 font-semibold flex items-center space-x-2">
                          <span>View Answer</span>
                          <FiArrowRight size={16} />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>

          {/* Tips Section */}
          <div className="bg-gradient-to-br from-cyan-50 to-blue-50 rounded-2xl p-12">
            <h2 className="text-4xl font-bold mb-12 text-slate-900">Interview Tips & Tricks</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {tips.map((tip, index) => (
                <div key={index} className="bg-white rounded-xl p-6 shadow-md hover:shadow-lg transition">
                  <div className="flex items-start space-x-4">
                    <FiCheckCircle className="text-cyan-500 text-2xl flex-shrink-0 mt-1" />
                    <div>
                      <h3 className="font-bold text-slate-900 mb-2">{tip.title}</h3>
                      <p className="text-gray-600 text-sm">{tip.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default InterviewPrep;
